runner:
  total_steps: 1000000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 5000
  eval_step: 10000
  save_step: 10000
  #log_step: 50
  #eval_step: 50
  #save_step: 50
  max_keep: 1
  eval_dataloaders:
    - dev
    - test
optimizer:
  name: AdamW
  #lr: 2.e-4
  lr: 2.e-4

downstream_expert:
  datarc:
    num_workers: 8
    train_batch_size: 32 
    #eval_batch_size: 32
    eval_batch_size: 32
    libri_root: '/$share/george_20120724_session1_CommonAve_ReginLabel/'
    #libri_root: '/home/negiryosuke/refine/s3prl/e_data_downstream_george_20120724_session1_20s_split/'
    split_file: '/$share/downstream/speaker_linear_utter_libri/data/'
    bucket_file: '/$share/george_20120724_session1_CommonAve_ReginLabel//E_data_len_for_bucket/'
    #bucket_file: '/home/negiryosuke/refine/s3prl/e_data_downstream_george_20120724_session1_20s_split/E_data_len_for_bucket'

    sample_rate: 16000 # this should not be changed, and this should match the sr of the audio in `libri_root`
    train_dev_seed: 1337

  modelrc: 
    none: None